<<<<<<< HEAD
title:            jcoelho
description:      on the edge
disqus_shortname: jcoelho
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              http://jest.pt

# Owner/author information
owner:
  name:           João Coelho
  avatar:         avatar.jpg
  bio:            "Bioanthropologist, datapreneur wannabe and R enthusiast"
  email:          joao@osteomics.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        Gangryong
  facebook:       
  github:         Delvis
  stackexchange:  
  linkedin:       jpvocoelho
  instagram:      delvispresley
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-68440862-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Portugal
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: JEST
title-normal: Junior Enterprise of Sciences and Tech
email: info@jest.pt
description: Providing solutions in life and data sciences.
baseurl: "/jestpt.github.io" # the subpath of your site, e.g. /blog
url: "http://jest.pt" # the base hostname & protocol for your site
author: JEST
street_address: Department of Life Sciences
city: Coimbra
zip_code: 3000-406
country: Portugal
phone: (716) 555-5555 * edit

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
>>>>>>> master
